### PR TITLE
chagne is_pessimistic_lock from bool to enum

### PR DESCRIPTION
**Pull request by ekexium**
ref: pingcap/tidb#36579

An experiment of supporting postponing some constraint check of pessimistic transactions.

### CODE REVIEW

**Review by sticnarf — APPROVED** [review]

**Comment by Connor1996** [comment]
Does it affect backward compatibility as you change the type of an existing field?

**Comment by ekexium** [comment]
> Does it affect backward compatibility as you change the type of an existing field?

They are all encoded as `varint`, so I suppose it's compatible.

**Comment by tiancaiamao** [comment]
> > Does it affect backward compatibility as you change the type of an existing field?
> 
> They are both encoded as `varint`, so I suppose it's compatible.

Usually we add new field, deprecate old field, but never change any field for the sake of compatibility

**Comment by tiancaiamao** [comment]
B.T.W, the tidb master branch can't build with this...

```
 make
CGO_ENABLED=1 GO111MODULE=on go build  -tags codes  -ldflags '-X "github.com/pingcap/tidb/parser/mysql.TiDBReleaseVersion=v6.3.0-alpha-110-ga75a5716f" -X "github.com/pingcap/tidb/util/versioninfo.TiDBBuildTS=2022-08-31 13:13:30" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitHash=a75a5716f47b45c5e1b95fc518273fc0103887a3" -X "github.com/pingcap/tidb/util/versioninfo.TiDBGitBranch=qos" -X "github.com/pingcap/tidb/util/versioninfo.TiDBEdition=Community" ' -o bin/tidb-server tidb-server/main.go
# github.com/tikv/client-go/v2/internal/mockstore/mocktikv
../../tikv/client-go/internal/mockstore/mocktikv/mvcc_leveldb.go:743:32: undefined: kvrpcpb.PrewriteRequest_SKIP_PESSIMISTIC_CHECK
../../tikv/client-go/internal/mockstore/mocktikv/mvcc_leveldb.go:744:14: req.PessimisticActions undefined (type *kvrpcpb.PrewriteRequest has no field or method PessimisticActions)
../../tikv/client-go/internal/mockstore/mocktikv/mvcc_leveldb.go:745:28: req.PessimisticActions undefined (type *kvrpcpb.PrewriteRequest has no field or method PessimisticActions)
../../tikv/client-go/internal/mockstore/mocktikv/mvcc_leveldb.go:878:28: undefined: kvrpcpb.PrewriteRequest_PessimisticAction
../../tikv/client-go/internal/mockstore/mocktikv/mvcc_leveldb.go:895:36: undefined: kvrpcpb.PrewriteRequest_DO_PESSIMISTIC_CHECK
../../tikv/client-go/internal/mockstore/mocktikv/mvcc_leveldb.go:920:35: undefined: kvrpcpb.PrewriteRequest_DO_PESSIMISTIC_CHECK
# github.com/tikv/client-go/v2/txnkv/transaction
../../tikv/client-go/txnkv/transaction/prewrite.go:77:39: undefined: kvrpcpb.PrewriteRequest_PessimisticAction
../../tikv/client-go/txnkv/transaction/prewrite.go:93:36: undefined: kvrpcpb.PrewriteRequest_DO_PESSIMISTIC_CHECK
../../tikv/client-go/txnkv/transaction/prewrite.go:95:36: undefined: kvrpcpb.PrewriteRequest_DO_CONSTRAINT_CHECK
../../tikv/client-go/txnkv/transaction/prewrite.go:97:36: undefined: kvrpcpb.PrewriteRequest_SKIP_PESSIMISTIC_CHECK
../../tikv/client-go/txnkv/transaction/prewrite.go:154:3: unknown field 'PessimisticActions' in struct literal of type kvrpcpb.PrewriteRequest
make: *** [Makefile:147: server] Error 2
```

I'm not using the latest client-go, so I'm not sure whether there is a corresponding update that works.

**Comment by ekexium** [comment]
> I'm not using the latest client-go, so I'm not sure whether there is a corresponding update that works.

There is, and will be updated soon. It works for me

**Pull request merged**
