### PR TITLE
raft_serverpb: add new ExtraMessage types for the snapshot gen precheck process

### PR DESCRIPTION
**Pull request by hbisheng**
Related issue: https://github.com/tikv/tikv/issues/15972

This commit adds two new new ExtraMessage types that are part of the snapshot
gen precheck process: Before a leader generates a snapshot, it sends a precheck
request to the target follower. The follower responds with a boolean value
indicating whether the check succeeds.

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by overvenus** [comment]
LGTM, let's hold this PR until the TiKV side implements and tests the functionality.

**Review by zhangjinpeng87 — COMMENTED** [review]
LGTM

**Review by overvenus — APPROVED** [review]

**Pull request merged**
