### PR TITLE
*: fix ugly default derive debug format

### PR DESCRIPTION
**Pull request by BusyJay**
The idea is to provide common debug format implement instead of relying on the the protobuf library.

Prost can also utilize the helper trait and function later.

### CODE REVIEW

**Comment by BusyJay** [comment]
Some logs from manual testing:
> async apply finish, res: ApplyRes { region_id: 1, apply_state: applied_index: 23 truncated_state { index: 17 term: 6 }, applied_index_term: 6, exec_res: [ChangePeer(ChangePeer { conf_change: change_type: RemoveNode node_id: 3 context: "\n\016\010\001\022\004\010\001\020\001*\004\010\007\020\001\032\014\010\001\022\010\010\001\022\004\010\003\020\003", peer: id: 3 store_id: 3, region: id: 1 region_epoch { conf_ver: 8 version: 1 } peers { id: 1 store_id: 1 } peers { id: 4 store_id: 2 } })], metrics: ApplyMetrics { size_diff_hint: 0, delete_keys_hint: 0, written_bytes: 72, written_keys: 2, lock_cf_written_bytes: 0 }, merged: false }, peer_id: 1, region_id: 1

**Comment by breeswish** [comment]
Why sometimes there are commas but sometimes not, and sometimes brace sometime none?

```
region_id: 1, apply_state: applied_index: 23
id: 3 store_id: 3

truncated_state { index: 17 term: 6 }
peer: id: 3 store_id: 3
```

**Comment by BusyJay** [comment]
Commas are added by the logs itself. Protobuf never outputs commas. Braces are added only when it's a message field.

**Comment by BusyJay** [comment]
Logs in master:

> executing task, task: heartbeat for region Region { id: 1, start_key: [], end_key: [], region_epoch: Some(RegionEpoch { conf_ver: 1, version: 1, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }), peers: [Peer { id: 1, store_id: 1, is_learner: false, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }], unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }, leader 1

Logs in this branch:

> executing task, task: heartbeat for region id: 1 region_epoch { conf_ver: 1 version: 1 } peers { id: 1 store_id: 1 }, leader 1

**Pull request closed without merging**
