### PR TITLE
add FollowerReadProxy

### PR DESCRIPTION
**Pull request by hicqu**
Add a new service `FollowerReadProxy`.

For follower read crossing multiple data centers, TiDBs can send requests to the service to get a timestamp and all committed indices for target regions.

Generally the service will run on TiKVs on the major data center.

### CODE REVIEW

**Comment by BusyJay** [comment]
Why not just add a method to kv service?

**Comment by hicqu** [comment]
@BusyJay not all TiKVs needs to register this service. By design, only TiKVs in the major data centers need this. And an another reason is we think seperate them can make code more clean.
Is there any advantage to merge them?

**Comment by BusyJay** [comment]
Union them can lead to more unify setup and reduce boilerplate codes. I think it may not be easy to identify whether it's a major data center, or whether it will become a major data center in the future.

**Comment by disksing** [comment]
Do we need to proceed with this pull request? cc @BusyJay @hicqu

**Comment by disksing** [comment]
Closing for inactivity.

**Pull request closed without merging**
