### PR TITLE
storage: Add checksum/split-region/import-write for rawkv

### PR DESCRIPTION
**Pull request by Little-Wallace**
Signed-off-by: Little-Wallace <bupt2013211450@gmail.com>

We want to support loading data into TiKV in RawKV mode by tidb-lightning. So we need to supply these method for tidb-lightning:

- RawWrite: to write data with RawKV-format rather than TxnKV-format.
- RawSplitRegion: tidb-lightning will split region into multiple ones to avoid write too many data in one region.
- RawChecksum: tidb-lightning will compare checksum-value between source data and data in TiKV. But TiKV used to supply TxnKV method for checksum and the checksum code is in `tidb` repo. So we need an independent method only for RawKV.

### CODE REVIEW

**Comment by nolouch** [comment]
RawSplitRegion-> what's the differnet with https://github.com/pingcap/kvproto/pull/743/files#diff-9012f74300ab5335dd6edf75bb4f95361c48f5454d4a0fb4c51864989ee2f3bfR89-R91？

**Comment by Little-Wallace** [comment]
> RawSplitRegion-> what's the differnet with [https://github.com/pingcap/kvproto/pull/743/files#diff-9012f74300ab5335dd6edf75bb4f95361c48f5454d4a0fb4c51864989ee2f3bfR89-R91？](https://github.com/pingcap/kvproto/pull/743/files#diff-9012f74300ab5335dd6edf75bb4f95361c48f5454d4a0fb4c51864989ee2f3bfR89-R91%EF%BC%9F)

Because the keys of request to rawsplitregion will not be encoded.

**Comment by disksing** [comment]
Hi @Little-Wallace @nolouch  do we need to continue it?

**Comment by disksing** [comment]
closing for inactivity

**Pull request closed without merging**
