### PR TITLE
add prefix key filter for tikv ctl

### PR DESCRIPTION
**Pull request by wentaoxu**
filter all the regions which size is larger than some limitation.

### CODE REVIEW

**Comment by wentaoxu** [comment]
PTAL @zhangjinpeng1987

**Comment by BusyJay** [comment]
Can this be implemented purely in tikv-ctl?

**Comment by wentaoxu** [comment]
@BusyJay I'm afraid not for `DebugClient`, we can't get metadata of the regions on one tikv server because `get_all_meta_regions` is not implemented, and we will get better performance in this way.

**Comment by wentaoxu** [comment]
after discussion with @zhangjinpeng1987 , I will change this to another way.

**Comment by wentaoxu** [comment]
PTAL @BusyJay @zhangjinpeng1987

**Comment by disksing** [comment]
closing for inactivity.

**Pull request closed without merging**
