### PR TITLE
Add `damaged_regions_id` for `StoreStats`

### PR DESCRIPTION
**Pull request by hunterlxt**
Add 3 operator modes for now

### CODE REVIEW

**Comment by disksing** [comment]
> @disksing actually, it resued server.handler

I mean can you use HTTP API directly instead using gRPC?

**Comment by hunterlxt** [comment]
> > @disksing actually, it resued server.handler
> 
> I mean can you use HTTP API directly instead using gRPC?

I'm worried about TLS etc. Unified into grpc may avoid some problems, we can configure the network(pd - tikv) uniformly

**Review by BusyJay — APPROVED** [review]
Giving that we have `GetOperator`, it seems reasonable to add an `AddOperator`.

**Comment by HunDunDM** [comment]
How to ensure the compatibility of move-peer?
And I don't think `GetOperator` should exist either, but it is an ancient existence #369 and cannot be deleted now. It should not be a reason to continue to add new ones.

**Review by HunDunDM — COMMENTED** [review]
lgtm

**Pull request merged**
