### PR TITLE
update to protobuf 3

### PR DESCRIPTION
**Pull request by BusyJay**
Update all proto files to syntax proto3.

### CODE REVIEW

**Comment by overvenus** [comment]
It is hard to review. Could you separate changes of proto and generated files into different commits?

**Comment by disksing** [comment]
LGTM.

**Comment by BusyJay** [comment]
Changes is sorted by name, so you can jump to the first proto, and then review all the proto changes without disturbance. @overvenus

**Comment by overvenus** [comment]
LGTM

**Comment by siddontang** [comment]
Any compatibility problem?  The new version server can handle old version? Or the old version server can handle new version?

**Comment by BusyJay** [comment]
They should be binary compatible.

**Comment by BusyJay** [comment]
From the API level, there is no way to tell missing field from an empty field without any other additional fields. So we may need to change the `GetResponse` message.

**Comment by BusyJay** [comment]
Looks like we can still check it by checking if `GetResponse` is set. Maybe `TiClient` needs to take care of this.  /cc @disksing

**Comment by disksing** [comment]
Now we simply do not allow empty value. So empty _Get_ response is the same with no _Get_ response.

**Pull request merged**
