### PR TITLE
Add latch wait and scheduler process time to WriteDetail

### PR DESCRIPTION
**Pull request by sticnarf**
Signed-off-by: Yilin Chen <sticnarf@gmail.com>

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@you06 @MyonKeminta @oneSizeFitsQuorum
We could discuss the proto detail here.

```
Update_5                     	root     	0      	N/A                                                                                                                                         	0      	time:1.48s, loops:5, lock_keys: {time:4.95ms, region:2, keys:2, slowest_rpc: {total: 0.005s, region_id: 2, store: 127.0.0.1:20260, tikv_wall_time: 4.55ms, scan_detail: {get_snapshot_time: 6.15µs, rocksdb: {key_skipped_count: 17099, block: {}}}, }, lock_rpc:4.9321ms, rpc_count:2, retry_count:1}                                                                                                                                                       	29.6 KB	N/A
	└─SelectLock_7               	root     	0.00   	for update 0                                                                                                                                	5      	time:1.48s, loops:10                                                                                                                                                                                                                                                                                                                                                                                                                                          	N/A    	N/A
	  └─IndexLookUp_10           	root     	0.00   	                                                                                                                                            	5      	time:26.9ms, loops:10, index_task: {total_time: 11.2ms, fetch_handle: 11.2ms, build: 2.21µs, wait: 6.37µs}, table_task: {total_time: 12.8ms, num: 5, concurrency: 5} 
```

There's such a case that the LOCK accumulation could slow down the pessimistic acquisition,
![image](https://user-images.githubusercontent.com/3692139/182998354-30106357-858c-45bc-a9ec-300fd0b8cf5d.png)

From current slow log information, it could not be checked directly as the read details is not recorded yet.

**Comment by sticnarf** [comment]
> We could discuss the proto detail here.
> 
> ```
> Update_5                     	root     	0      	N/A                                                                                                                                         	0      	time:1.48s, loops:5, lock_keys: {time:4.95ms, region:2, keys:2, slowest_rpc: {total: 0.005s, region_id: 2, store: 127.0.0.1:20260, tikv_wall_time: 4.55ms, scan_detail: {get_snapshot_time: 6.15µs, rocksdb: {key_skipped_count: 17099, block: {}}}, }, lock_rpc:4.9321ms, rpc_count:2, retry_count:1}                                                                                                                                                       	29.6 KB	N/A
> 	└─SelectLock_7               	root     	0.00   	for update 0                                                                                                                                	5      	time:1.48s, loops:10                                                                                                                                                                                                                                                                                                                                                                                                                                          	N/A    	N/A
> 	  └─IndexLookUp_10           	root     	0.00   	                                                                                                                                            	5      	time:26.9ms, loops:10, index_task: {total_time: 11.2ms, fetch_handle: 11.2ms, build: 2.21µs, wait: 6.37µs}, table_task: {total_time: 12.8ms, num: 5, concurrency: 5} 
> ```
> 
> There's such a case that the LOCK accumulation could slow down the pessimistic acquisition,

The "block" part is empty probably because it's in the memtable... Is the huge `key_skipped_count` enough to diagnose the problem?

**Comment by cfzjywxk** [comment]
> > We could discuss the proto detail here.
> > ```
> > Update_5                     	root     	0      	N/A                                                                                                                                         	0      	time:1.48s, loops:5, lock_keys: {time:4.95ms, region:2, keys:2, slowest_rpc: {total: 0.005s, region_id: 2, store: 127.0.0.1:20260, tikv_wall_time: 4.55ms, scan_detail: {get_snapshot_time: 6.15µs, rocksdb: {key_skipped_count: 17099, block: {}}}, }, lock_rpc:4.9321ms, rpc_count:2, retry_count:1}                                                                                                                                                       	29.6 KB	N/A
> > 	└─SelectLock_7               	root     	0.00   	for update 0                                                                                                                                	5      	time:1.48s, loops:10                                                                                                                                                                                                                                                                                                                                                                                                                                          	N/A    	N/A
> > 	  └─IndexLookUp_10           	root     	0.00   	                                                                                                                                            	5      	time:26.9ms, loops:10, index_task: {total_time: 11.2ms, fetch_handle: 11.2ms, build: 2.21µs, wait: 6.37µs}, table_task: {total_time: 12.8ms, num: 5, concurrency: 5} 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There's such a case that the LOCK accumulation could slow down the pessimistic acquisition,
> 
> The "block" part is empty probably because it's in the memtable... Is the huge `key_skipped_count` enough to diagnose the problem?

Seem the `key_skipped_count` gives information about it, I'm thinking about something like the cop details and didn't notice it at first.

**Comment by cfzjywxk** [comment]
```
Insert_1	root	0      	N/A          	0      	time:15ms, loops:1, prepare: 3.3ms, insert:11.7ms, commit_txn: {prewrite:245.9ms, get_commit_ts:2.17ms, commit:840ms, backoff: {time: 444ms, type: [pdRPC]}, slowest_commit_rpc: {total: 0.244s, region_id: 1007, store: 127.0.0.1:20260, tikv_wall_time: 242.5ms, scan_detail: {get_snapshot_time: 2.62µs, rocksdb: {block: {cache_hit_count: 89}}}, write_detail: {store_batch_wait: 47.2ms, propose_send_wait: 0s, persist_log: {total: 39.5ms, write_leader_wait: 774.2µs, sync_log: 18ms, write_memtable: 32.9µs}, commit_log: 39.6ms, apply_batch_wait: 101.7ms, apply: {total:47.3ms, mutex_lock: 109ns, write_leader_wait: 0s, write_wal: 101.7ms, write_memtable: 485.1µs}}}, region_num:1, write_keys:2662, write_byte:574992}	1.73 MB	N/A
```

Another two-phase commit slow query case, the total query time is 1.1s, from the slow log we could know that the `prewrite:245.9ms` and ` commit:840ms`, but it's a bit difficult to verify the root cause of the slowness directly.

**Comment by sticnarf** [comment]
> ```
  > Insert_1	root	0      	N/A          	0      	time:15ms, loops:1, prepare: 3.3ms, insert:11.7ms, commit_txn: {prewrite:245.9ms, get_commit_ts:2.17ms, commit:840ms, backoff: {time: 444ms, type: [pdRPC]}, slowest_commit_rpc: {total: 0.244s, region_id: 1007, store: 127.0.0.1:20260, tikv_wall_time: 242.5ms, scan_detail: {get_snapshot_time: 2.62µs, rocksdb: {block: {cache_hit_count: 89}}}, write_detail: {store_batch_wait: 47.2ms, propose_send_wait: 0s, persist_log: {total: 39.5ms, write_leader_wait: 774.2µs, sync_log: 18ms, write_memtable: 32.9µs}, commit_log: 39.6ms, apply_batch_wait: 101.7ms, apply: {total:47.3ms, mutex_lock: 109ns, write_leader_wait: 0s, write_wal: 101.7ms, write_memtable: 485.1µs}}}, region_num:1, write_keys:2662, write_byte:574992}	1.73 MB	N/A
> ```
> 
> Another two-phase commit slow query case, the total query time is 1.1s, from the slow log we could know that the `prewrite:245.9ms` and ` commit:840ms`, but it's a bit difficult to verify the root cause of the slowness directly.

Here there are a few issues. For a transaction that does not use async commit, the execution details of commit should be included. And the most dominant part seems to be the pdRPC backoff, but an error type should be more informative than a backoff type.

**Comment by OneSizeFitsQuorum** [comment]
Hi, I would love to learn how to collect these metrics. I have briefly read the collection method of other fields of `WriteDetail`, and I think it is mainly necessary to find the corresponding code block. I am reading the relevant source code to learn the process of TiKV. However, I don't know how we will cooperate in the future. Will we first merge this PR, then update TiKV's dependence on kvproto, and then continue to add corresponding monitoring on TiKV?

**Comment by sticnarf** [comment]
> Hi, I would love to learn how to collect these metrics. I have briefly read the collection method of other fields of `WriteDetail`, and I think it is mainly necessary to find the corresponding code block. I am reading the relevant source code to learn the process of TiKV. However, I don't know how we will cooperate in the future. Will we first merge this PR, then update TiKV's dependence on kvproto, and then continue to add corresponding monitoring on TiKV?

A few days ago, @cfzjywxk had some disagreements on how to organize these fields. If we agree on the changes from this PR, we can merge it.

If you want to add other metrics fields, you can create a similar pull request like this. The review process of kvproto can be parallel with TiKV. You can write the TiKV/client-go code meanwhile with a patched kvproto.

**Comment by cfzjywxk** [comment]
@sticnarf @OneSizeFitsQuorum 
We could merge this pr first and keep it simple by now, using the `WriteDetail` to represent the write commands processed in the tikv-server.

**Review by cfzjywxk — APPROVED** [review]

**Review by zyguan — APPROVED** [review]
LGTM

**Pull request merged**
