### PR TITLE
PessimisticLock: signed wait timeout

### PR DESCRIPTION
**Pull request by youjiali1995**
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>

### CODE REVIEW

**Comment by coocood** [comment]
@sticnarf PTAL

**Comment by coocood** [comment]
@MyonKeminta PTAL

**Comment by coocood** [comment]
> Maybe better to comment for what negative value means?

+1
And comment for 0 value means default.

**Comment by youjiali1995** [comment]
@coocood @sticnarf PTAL again. Thanks!

**Pull request merged**
