### PR TITLE
add reverse option in RawBatchScanRequest

### PR DESCRIPTION
**Pull request by kamijin-fanta**
- support backward scan
- for https://github.com/tikv/tikv/issues/3705

### CODE REVIEW

**Comment by MyonKeminta** [comment]
In fact, I suggest you also update RawScan because currently it seems that the go client doesn't support RawBatchScan...

**Comment by kamijin-fanta** [comment]
also possible to change both.
raw_batch_scan internally use raw_scan.

**Comment by MyonKeminta** [comment]
Yes, I suggest that you add the `reverse` field in both `RawScanRequest` and `RawBatchScanRequest`

**Comment by kamijin-fanta** [comment]
oh sorry. change it like that.

**Comment by kamijin-fanta** [comment]
changed it

**Comment by kamijin-fanta** [comment]
@overvenus @MyonKeminta changed it. please review.

**Pull request merged**
