### PR TITLE
raft_cmdpb: Add region to ChangePeerRequest.

### PR DESCRIPTION
**Pull request by ngaut**

### CODE REVIEW

**Comment by ngaut** [comment]
PTAL @siddontang @BusyJay

**Comment by siddontang** [comment]
should we only contain version fields? 
btw, split also need this.

**Comment by ngaut** [comment]
Region is small, let's just contain all the information now.

**Comment by ngaut** [comment]
PTAL @siddontang

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
