### PR TITLE
pdpb: add SplitRegion command.

### PR DESCRIPTION
**Pull request by disksing**
When tikv receives the SplitRegion command, it should split the region into 2 parts. It is encouraged to make the 2 region have the same size.

### CODE REVIEW

**Comment by overvenus** [comment]
Would you mind add some descriptions?

**Comment by disksing** [comment]
Here is the comment: https://github.com/pingcap/kvproto/pull/229/files#diff-302367292c5ac90dc53f4a17d1851bcbR286
@overvenus

**Comment by BusyJay** [comment]
How to ensure the command won't be sent or executed multiple times concurrently?

**Comment by disksing** [comment]
@BusyJay The command contains the region's epoch. tikv-sever may check if its version matches the command to decide whether to execute the command.

**Comment by AndreMouche** [comment]
LGTM

**Pull request merged**
