### PR TITLE
Update raft dependency to 0.4.0.

### PR DESCRIPTION
**Pull request by Hoverbear**
Raft 0.4.0 was released and we'd like to update TiKV to use it. It's blocked on this PR.

### CODE REVIEW

**Comment by hicqu** [comment]
LGTM.

**Comment by Hoverbear** [comment]
@BusyJay PTAL

**Comment by Hoverbear** [comment]
@overvenus I copied the new eraftpb.proto over, it has an extra comment.

It seems when I run `make` though it generates many many changes. Is it not necessary for a PR? Or does it need to be done as well?

**Comment by overvenus** [comment]
Yes, please push the changes since you change a proto file.

**Comment by Hoverbear** [comment]
@overvenus PTAL

**Comment by Hoverbear** [comment]
I think this is blocked by #303

**Comment by Hoverbear** [comment]
ping @hicqu

**Comment by Hoverbear** [comment]
@overvenus @hicqu PTAL, I'd really like to merge this. It is related to https://github.com/tikv/tikv/issues/3836 and https://github.com/tikv/tikv/issues/3632.

**Comment by hicqu** [comment]
LGTM

**Pull request merged**
