### PR TITLE
proto: add cpu count in store heartbeat

### PR DESCRIPTION
**Pull request by huachaohuang**
Balance leader according to store cpu count.

### CODE REVIEW

**Comment by siddontang** [comment]
why PD needs this?

**Comment by huachaohuang** [comment]
We may deploy TiKV in machines with different number of cpus, we can adjust leader count according to cpu count.

**Comment by huachaohuang** [comment]
For example, if store 1 has 24 cpus, store 2 has 48 cpus, and we have 72 regions, we can put 24 leaders to store1 and put 48 leaders to store 2.

**Comment by siddontang** [comment]
But we only have one raftstore, the write load will be very high in store 2 with 48 leaders

**Comment by huachaohuang** [comment]
OK, I see, then we should avoid deployment in heterogeneous machines.

**Pull request closed without merging**
