### PR TITLE
raftpb: port transfer leader feature from etcd

### PR DESCRIPTION
**Pull request by tiancaiamao**

### CODE REVIEW

**Comment by siddontang** [comment]
I guess your protoc C version is not the same with us.

**Comment by tiancaiamao** [comment]
I change to libprotoc 2.6.0, and `cargo install protobuf`, which is now protobuf:1.0.20
but it still generate different files.
would you please paste your environment? @siddontang

**Comment by ngaut** [comment]
LGTM
PTAL @siddontang

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
