### PR TITLE
add a option to link system grpc lib

### PR DESCRIPTION
**Pull request by nooberfsh**

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @nooberfsh 

Can you tell me when do we need this feature?

**Comment by nooberfsh** [comment]
@siddontang 
It toke a lot of time to build Tikv. Tikv depend on grpcio and kvproto,  both of them need grpc lib. link a system grpc lib would save a lot of build time.
If this PR will be accpeted, I will send  another PR similar to this one to Tikv repo.

**Comment by BusyJay** [comment]
I don't think it's a good idea to enable static/dynamic linking via features now. I propose to use environment variable to control this instead. So even we introduce more native dependencies in the future, users can still control linking to which dependency dynamically as they want.

**Comment by nooberfsh** [comment]
you are right,  use environment variable is a better  way.

**Pull request closed without merging**
