### PR TITLE
raftstore: add start_key and end_key to RaftMessage

### PR DESCRIPTION
**Pull request by BusyJay**
ref pingcap/tikv#1217

@siddontang @zhangjinpeng1987 @hhkbp2 PTAL

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
Why are other files changed too?

**Comment by BusyJay** [comment]
I guess the original sources are outdated.

**Comment by siddontang** [comment]
LGTM

**Comment by hhkbp2** [comment]
LGTM

**Pull request merged**
