### PR TITLE
pdpb: add a new field `id`

### PR DESCRIPTION
**Pull request by overvenus**
Since PDs are usually deployed in different machine, PID becomes a non-unique value, especially runs in a **docker container**.

This PR renames PID(int64) to ID(uint64). It changes the type, so PD, TiKV and TiDB need a update later.  

PTAL @siddontang @huachaohuang 

Address https://github.com/pingcap/pd/issues/442#issuecomment-267274193

### CODE REVIEW

**Comment by huachaohuang** [comment]
LGTM

**Comment by siddontang** [comment]
Please keep backend compatibility, add a new field ID.

**Comment by overvenus** [comment]
Em~ There is a workaround, let's keep using `int64 Pid`(PD's ID ;-)), _`uint64` can **fit** in `int64`_, we can cast uint64 to int64  in PD, TiKV and TiDB.

@siddontang @huachaohuang @shenli

**Comment by siddontang** [comment]
PID is usually for process ID. 
I still think it is better to use another ID field.

**Comment by overvenus** [comment]
@siddontang Well, we can think PID is short for Placement Driver's ID.

What's your opinion? @huachaohuang

**Comment by siddontang** [comment]
It is not a good habit to change the origin meaning of the protocol. 
Why not using a new field? Hurting the performance or causing complex code?

**Comment by overvenus** [comment]
No particular reason. Okay, add a new filed.

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @huachaohuang

**Comment by huachaohuang** [comment]
If the pid field will be used anymore?
If not, I suggest comment it out and add some comments about it.

**Comment by huachaohuang** [comment]
LGTM

**Pull request merged**
