### PR TITLE
Update some deps

### PR DESCRIPTION
**Pull request by nrc**
In particular use a branch of rust-protobuf 2.8 which includes support for rendering bytes as hex.

### CODE REVIEW

**Comment by breeswish** [comment]
Is it possible to support render bytes as hex in kvproto instead of in a common infra like rust-protobuf, since it is a specialized demand only for TiDB product stack?

**Comment by nrc** [comment]
> Is it possible to support render bytes as hex in kvproto instead of in a common infra like rust-protobuf, since it is a specialized demand only for TiDB product stack?

Not really. at the very least we need some trait in kvproto to implement in our crates and I think landing that would be troublesome (we never landed the `PbPrint`in the original patches). We also need to maintain a fork for other reasons, so I don't think it is worth trying to. I do think that rendering bytes as hex is useful outside of TiDB, I think if we end up using the bytes crate with either rust-proto or Prost, we should get rendering of hex there (I'm sure if it is there already, but I'm sure we could add it).

**Comment by BusyJay** [comment]
I would say that the original format is the standard format of protobuf, all implementations follow the similar format. Rendering in hex is actually some special requirement from our own project.

**Comment by siddontang** [comment]
maybe @nrc can build another tool based on protobuf-build to generate our specialized format codes.

**Comment by nrc** [comment]
For now I think we can either land this as is (pretty much like what we had previously) or we can forget about the hex formatting. We can perhaps improve later (e.g., by working with rust-protobuf to add hook traits or do something in protobuf-build), but I think this is a small thing and we should get this landed and move on.

**Pull request merged**
