### PR TITLE
Add SplitRegion API

### PR DESCRIPTION
**Pull request by overvenus**
CC https://github.com/pingcap/tikv/issues/2270

### CODE REVIEW

**Comment by disksing** [comment]
LGTM.

**Comment by zhangjinpeng1987** [comment]
LGTM

**Comment by overvenus** [comment]
Waiting pingcap/tikv#2287 .

**Comment by overvenus** [comment]
PTAL @disksing @BusyJay

**Comment by disksing** [comment]
LGTM

**Comment by disksing** [comment]
Can we merge this PR? cc @overvenus

**Comment by overvenus** [comment]
Sure, all things are settled down, I think.

**Pull request merged**
