### PR TITLE
debug: add MetaRegions RPC.

### PR DESCRIPTION
**Pull request by hicqu**
This RPC returns all meta regions' id. It can be used for running some debug commands in remot mode, such as `raft region info`.

### CODE REVIEW

**Comment by hicqu** [comment]
@BusyJay @overvenus , PTAL.

**Comment by hicqu** [comment]
@BusyJay @overvenus PTAL

**Comment by BusyJay** [comment]
What is a meta region?

**Comment by hicqu** [comment]
The name is unclear. In fact, this API returns regions have any keys between `REGION_META_MIN_KEY` and `REGION_META_MAX_KEY`.

**Pull request closed without merging**
