### PR TITLE
Prost support

### PR DESCRIPTION
**Pull request by nrc**
This adds Prost code generation and the generated Prost files. It is not ready to land since it's missing wrappers to make the Prost code compatible with the rust-protobuf code.

### CODE REVIEW

**Comment by siddontang** [comment]
> It is not ready to land since it's missing wrappers to make the Prost code compatible with the rust-protobuf code.

Have you evaluated how much time do we need to add a wrapper? I guess `set`, `get` fields functions may be easy, right?

**Comment by nrc** [comment]
> Have you evaluated how much time do we need to add a wrapper?

Oh, I have done that now. Merging is blocked on getting some PRs landed in Prost (in progress).

**Comment by hicqu** [comment]
Hi @nrc do you have any progress? In latest raft-rs prost is used, so if we want to use  that in TiKV, we will also need prost in kvproto, I guess. Please @ me if I can do something.

**Comment by nrc** [comment]
@overvenus @siddontang PTAL this is ready to merge now

@hicqu it uses the 0.4.1 branch of Raft which does not include joint consensus, etc

**Pull request merged**
