### PR TITLE
backup.proto: rename backup.proto to solve name conflict with badger …

### LINKED ISSUE #790: Rename backup.proto to solve name conflict with badger
github.com/pingcap/badger also has the backup.proto, so when we merge the BR code into TiDB, it will cause panic due to conflict file name `backup.proto`.

### PR DESCRIPTION
**Pull request by 3pointer**
…in merging BR into TiDB

closes #790 

github.com/pingcap/badger also has the backup.proto, so when we merge the BR code into TiDB, it will cause panic due to conflict file name `backup.proto`.

### CODE REVIEW

**Comment by kennytm** [comment]
should we change the package name 🤔 

https://github.com/pingcap/kvproto/blob/dd85fc377bc77ac7d56a9d18a6b6c4d5ae0440b4/proto/brpb.proto#L2

**Comment by disksing** [comment]
Do we need to proceed with this pull request? cc @3pointer

**Comment by disksing** [comment]
closing for inactivity.

**Comment by 3pointer** [comment]
> Do we need to proceed with this pull request? cc @3pointer

Yes, we need this PR if we want to merge BR into TiDB.

**Review by disksing — APPROVED** [review]

**Review by YuJuncen — APPROVED** [review]

**Review by glorv — APPROVED** [review]

**Comment by coocood** [comment]
> @coocood do you mean that we can remove the proto in pingcap/badger since it is our own fork?

yes

**Pull request merged**
