### PR TITLE
pdpb.proto: revert and merge old config

### PR DESCRIPTION
**Pull request by HuSharp**
Signed-off-by: husharp <jinhao.hu@pingcap.com>

revert global config to make sure compatible
https://github.com/pingcap/kvproto/blob/7b9ea73af4b316813647100b0d1768aef81cf738/proto/pdpb.proto#L105-L134

### CODE REVIEW

**Review by nolouch — COMMENTED** [review]
lgtm

**Review by Connor1996 — APPROVED** [review]
LGTM

**Comment by HuSharp** [comment]
I will compile TiDB/PD/CDC firstly.

**Comment by HuSharp** [comment]
> I will compile TiDB/PD/CDC firstly.

Build all successfully, PTAL thx!!! @nolouch @Connor1996 @glorv

**Pull request merged**
