### PR TITLE
Use GitHub Actions to run the tests

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

The free resources of CircleCI are not enough to support the running of Rust tests. So I move all tests to use the GitHub Actions instead.

### CODE REVIEW

**Comment by JmPotato** [comment]
You can see some running examples [here](https://github.com/JmPotato/kvproto/actions).

**Comment by nolouch** [comment]
seems the GitHub action not running?

**Comment by overvenus** [comment]
LGTM

**Review by overvenus — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by overvenus** [comment]
Please also cherry-pick this PR to release-4.0 and release-3.0, because there is no CI running for PRs targets to these branch.

**Comment by nolouch** [comment]
cc @JmPotato

**Pull request merged**
