### PR TITLE
kvrpcpb: update KeyError add a WriteConflict field

### PR DESCRIPTION
**Pull request by tiancaiamao**
If the information of write conflict is a struct rather than a string, it's easier for TiDB to print a user friendly log.

```
Txn(Mvcc(WriteConflict { start_ts: 399402937522847774, conflict_ts: 399402937719455
772, key: [116, 128, 0, 0, 0, 0, 0, 1, 255, 155, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 1, 82, 8
7, 48, 49, 255, 0, 0, 0, 0, 251, 1, 55, 54, 255, 56, 50, 50, 49, 49, 48, 255, 57, 255, 0, 0, 0, 0
, 0, 0, 0, 248, 255, 1, 0, 0, 0, 0, 0, 0, 0, 255, 0, 247, 0, 0, 0, 0, 0, 0, 249], primary: [116,
128, 0, 0, 0, 0, 0, 1, 155, 95, 105, 128, 0, 0, 0, 0, 0, 0, 1, 1, 82, 87, 48, 49, 0, 0, 0, 0, 251
, 1, 55, 54, 56, 50, 50, 49, 49, 48, 255, 57, 0, 0, 0, 0, 0, 0, 0, 248, 1, 0, 0, 0, 0, 0, 0, 0, 0
, 247] }))
```

@AndreMouche @disksing

### CODE REVIEW

**Comment by disksing** [comment]
LGTM.

**Comment by tiancaiamao** [comment]
CI fail because the vendor and GOPATH environment. I just remove `go build` from Makefile
PTAL @disksing  @coocood

**Comment by breeswish** [comment]
LGTM

**Comment by coocood** [comment]
@tiancaiamao please resolve the conflict

**Pull request merged**
