### PR TITLE
split v2

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
Right region derive the original region id.
@BusyJay @hhkbp2 PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
I prefer using a flag in SplitRequest to indicate new region should be left or right.

**Comment by zhangjinpeng1987** [comment]
@BusyJay @siddontang PTAL

**Comment by hhkbp2** [comment]
LGTM

**Pull request merged**
