### PR TITLE
encryption: add encryption protobuf messages 

### PR DESCRIPTION
**Pull request by overvenus**
Add encryption protobuf messages.

Note: this PR also replaces nrc/rusr-protobuf with tikv/rust-protobuf as the former does not support map fields currently https://github.com/nrc/rust-protobuf/pull/1

### CODE REVIEW

**Comment by overvenus** [comment]
Seems protobuf-build does not support prost. Would you mind take a look? @nrc

**Comment by nrc** [comment]
> Seems protobuf-build does not support prost. Would you mind take a look? @nrc

I'm on vacation this week, but I'll take a look on Monday. (I have merged nrc/rust-protobuf#1).

**Comment by overvenus** [comment]
Have a nice vacation!

Map is supported by https://github.com/tikv/protobuf-build/pull/35

**Comment by overvenus** [comment]
> Note: this PR also replaces nrc/rusr-protobuf with tikv/rust-protobuf as the former does not support map fields currently nrc/rust-protobuf#1

> (I have merged nrc/rust-protobuf#1).

FYI, can not switch to nrc/rust-protobuf as the package name is changed to nrc-protobuf, and can not replace protobuf any more.

**Pull request merged**
