### PR TITLE
Make the package name and file name for deadlock.pb match

### PR DESCRIPTION
**Pull request by nrc**
A minor change, I see no reason why the package name and file name should be different (they are the same for all the other protos). Having them the same makes life easier because it means the Prost and rust-protobuf generated modules will have the same name.

PTAL @BusyJay @overvenus

### CODE REVIEW

**Comment by BusyJay** [comment]
Is the change backward compatible? I think it may make upgrade process broken as the service path will be changed too.

**Comment by nrc** [comment]
It is not backwards compatible, but when we do update kvproto, the change is very easy (for all of TiKV, we only need to change four imports) and I will send a PR as soon as this one lands. Since kvproto is in the lock file, we can't unintentionally update and break anything.

**Comment by siddontang** [comment]
PTAL @youjiali1995

**Comment by BusyJay** [comment]
What I mean is physically upgrading TiKV nodes. All transactions from tidb may fail.

**Comment by nrc** [comment]
> What I mean is physically upgrading TiKV nodes. All transactions from tidb may fail.

@BusyJay I see. Could you explain how that happens please? I don't understand what happens in that scenario.

**Comment by youjiali1995** [comment]
The service path is changed, so when TiKVs are upgrading, some requests will fail due to service not found. 

The pessimistic transaction feature is not used, and even if some requests fail, it is not a big deal because it's rare to cause deadlock and TiKV will retry.

**Comment by nrc** [comment]
Thanks for the explanation @youjiali1995 !

**Comment by BusyJay** [comment]
This should be done to release-3.0 too.

**Pull request merged**
