### PR TITLE
*: include proto files

### PR DESCRIPTION
**Pull request by overvenus**
Explicitly include google and gogoproto proto files.

PTAL @siddontang @BusyJay @disksing

### CODE REVIEW

**Comment by BusyJay** [comment]
Why?

**Comment by overvenus** [comment]
For better structure and understanding.

**Comment by BusyJay** [comment]
A simpler and cleaner way to do that is create a directory soft link. Although I don't see the point of doing it. Will the deleted files be created again once vendor is updated?

**Comment by overvenus** [comment]
No, they are no longer be kept. https://github.com/pingcap/kvproto/pull/176/files#diff-b67911656ef5d18c4ae36cb6741b7965R5

**Pull request closed without merging**
