### PR TITLE
pd: add api to put/get kv on kvbase

### PR DESCRIPTION
**Pull request by wentaoxu**
as title says
PTAL @zhangjinpeng1987 @disksing @Connor1996

### CODE REVIEW

**Comment by disksing** [comment]
LGTM.

**Comment by disksing** [comment]
Now this PR has nothing to do with GC. I think the title need update.

**Comment by wentaoxu** [comment]
ok @disksing

**Comment by disksing** [comment]
`kvbase` is an internal concept of pd. I think better to use `etcd` instead.

**Pull request closed without merging**
