### PR TITLE
pd: add TransferLeader RPC.

### PR DESCRIPTION
**Pull request by hicqu**
This PR will allow we call `transfer leader` API of PD from tikv-ctl.

### CODE REVIEW

**Comment by disksing** [comment]
Can't use HTTP api to add an operator?

**Comment by siddontang** [comment]
TiKV doesn't support HTTP.

But seem we can use pd-ctl to support this feature.

**Comment by siddontang** [comment]
I prefer using HTTP too.

**Comment by hicqu** [comment]
Got it. I will check how `pd-ctl` call that API.

**Pull request closed without merging**
