### PR TITLE
[DNM] *: add region local state

### PR DESCRIPTION
**Pull request by siddontang**
@ngaut @BusyJay @disksing

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by BusyJay** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @ngaut @BusyJay

**Comment by ngaut** [comment]
LGTM

**Comment by BusyJay** [comment]
PTAL

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
