### PR TITLE
add bucket swich for tikv

### PR DESCRIPTION
**Pull request by bufferflies**
Signed-off-by: bufferflies <1045931706@qq.com>

### CODE REVIEW

**Comment by bufferflies** [comment]
@youjiali1995 @disking

**Review by youjiali1995 — COMMENTED** [review]
I can't get it... Can you elaborate more on it?

**Comment by BusyJay** [comment]
I thought the conclusion was to keep the current behavior that use configurations on both PD and TIKV to decide whether buckets are enabled for this sprint.

**Comment by bufferflies** [comment]
> I can't get it... Can you elaborate more on it?

PD will notice tikv by PutStore and HeartBeat rpc.

**Comment by bufferflies** [comment]
> I thought the conclusion was to keep the current behavior that use configurations on both PD and TIKV to decide whether buckets are enabled for this sprint.

In past, pd can depence on the buckets stream is open to decide the buckets behavior.

**Comment by bufferflies** [comment]
it will use tikv config continue.

**Pull request closed without merging**
