### PR TITLE
Add leader field for region syncer

### PR DESCRIPTION
**Pull request by JmPotato**
Signed-off-by: JmPotato <ghzpotato@gmail.com>

Add `region_leaders` field for Region Syncer of PD. Related to [pingcap/pd#2591](https://github.com/pingcap/pd/pull/2591).

### CODE REVIEW

**Comment by nolouch** [comment]
remember to cherry-pick to release 4.0 .

**Comment by JmPotato** [comment]
> remember to cherry-pick to release 4.0 .

This branch, right? https://github.com/pingcap/kvproto/tree/release-4.0

**Comment by nolouch** [comment]
@JmPotato  Yes.

**Pull request merged**
