### PR TITLE
*: use protocbuf 1.0.20

### PR DESCRIPTION
**Pull request by siddontang**
@ngaut @BusyJay @disksing @tiancaiamao

### CODE REVIEW

**Comment by ngaut** [comment]
We should merge #53 first.

**Comment by tiancaiamao** [comment]
LGTM

**Comment by BusyJay** [comment]
L11 in `generate_rust.sh` can be deleted.

I think merge which first are both ok.

**Comment by siddontang** [comment]
@ngaut  
This is the base PR, #53 should merge this first, then sent again with only leader transfer support.

**Comment by ngaut** [comment]
LGTM

**Comment by disksing** [comment]
LGTM

**Pull request merged**
