### PR TITLE
*: add down_peers field.

### PR DESCRIPTION
**Pull request by huachaohuang**
Seems my rust-protobuf changes all `x.iter()` to `&x`, PTAL.

### CODE REVIEW

**Comment by siddontang** [comment]
do you use the newest rust protocol? should we all upgrade?

**Comment by ngaut** [comment]
We should update. @siddontang

**Comment by huachaohuang** [comment]
It's related to this commit [rust-protobuf](https://github.com/stepancheg/rust-protobuf/commit/6a582d1ac35b4cc7b1b6a87fa7eaee51c4637596).
I use the newest rust-protobuf, PTAL.

**Comment by ngaut** [comment]
LGTM

**Comment by ngaut** [comment]
PTAL @siddontang

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
