### PR TITLE
Unify proto options and do not generate unused fields

### PR DESCRIPTION
**Pull request by overvenus**
Unify proto options and do not generate unused fields by setting following options.

```
option (gogoproto.goproto_unkeyed_all) = false;
option (gogoproto.goproto_unrecognized_all) = false;
option (gogoproto.goproto_sizecache_all) = false;
```

Tests:

```shell
# pwd: kvproto
cd ../kvproto
git diff
diff --git a/go.mod b/go.mod
index 5dedb0a4f1..7671cd8042 100644
--- a/go.mod
+++ b/go.mod
@@ -326,4 +326,6 @@ replace (
        // Please remove these dependencies.
        sourcegraph.com/sourcegraph/appdash => github.com/sourcegraph/appdash v0.0.0-20190731080439-ebfcffb1b5c0
        sourcegraph.com/sourcegraph/appdash-data => github.com/sourcegraph/appdash-data v0.0.0-20151005221446-73f23eafcf67
+
+        github.com/pingcap/kvproto => ../kvproto
 )
make       
CGO_ENABLED=1  GO111MODULE=on go build -tags codes  -ldflags '-X "github.com/pingcap/tidb/pkg/parser/mysql.TiDBReleaseVersion=v8.5.0-alpha-41-g4cfe22cfa0-dirty" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBBuildTS=2024-11-05 07:39:00" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitHash=4cfe22cfa02490ed8e574f86a54d366404e111e1" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBGitBranch=master" -X "github.com/pingcap/tidb/pkg/util/versioninfo.TiDBEdition=Community" ' -o bin/tidb-server ./cmd/tidb-server
Build TiDB Server successfully!
```

Cc https://github.com/pingcap/tipb/pull/347 a complement PR for tipb.

### CODE REVIEW

**Review by cfzjywxk — APPROVED** [review]
LGTM

**Review by BornChanger — APPROVED** [review]

**Review by tiancaiamao — APPROVED** [review]

**Review by flowbehappy — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Comment by zhangjinpeng87** [comment]
What will happen during upgrading if new version add a new filed in the proto, and old version received the new message? @overvenus

**Comment by overvenus** [comment]
> What will happen during upgrading if new version add a new filed in the proto, and old version received the new message? 

If the old version receives the new message, it will discard new fields unless `goproto_unrecognized_all` is set to true. In that case, new fields will be stored in the `XXX_unrecognized []byte` field in binary form.

Both TiDB, PD and their tools are not using the `XXX_unrecognized`, making it essentially dead code, which is ok to remove.

**Review by zhangjinpeng87 — APPROVED** [review]
LGTM

**Review by MyonKeminta — APPROVED** [review]

**Review by you06 — APPROVED** [review]
This PR LGTM, but pay attention that the padding in TiDB need to be removed

https://github.com/pingcap/tidb/blob/5129bb37dd49d38f0d174e327c92345b4565caf6/pkg/kv/key.go#L102-L104

**Pull request merged**
