### PR TITLE
Vendor gogo

### LINKED ISSUE #128: Use specific gogo proto version
Now, small changes in `.proto` files may lead **huge** changes across all generated `.go` files, and some of them are not even related. I think it is caused by an ambiguous gogo/protobuf generator.

We can use glide to resolved this problem, just like what we've done in [tidb/Makefile](https://github.com/pingcap/tidb/blob/master/Makefile#L13).

cc @siddontang @shenli @ngaut

### PR DESCRIPTION
**Pull request by overvenus**
Please review commits: 
 - Makefile and other scripts: https://github.com/pingcap/kvproto/commit/f6aa0ac664be422977645e7c68e785e009e1ef75 
 - generated `.go` and `.rs`: https://github.com/pingcap/kvproto/commit/709a23e259f3241e602afa23bd0e21d8616b3785

PTAL @siddontang @ngaut @BusyJay 

Close #128

### CODE REVIEW

**Comment by siddontang** [comment]
how about rust?

**Comment by overvenus** [comment]
I think it has been handled by Cargo.lock.

**Comment by siddontang** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
